FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /app

COPY ./CopaMundoFilmes.Api ./CopaMundoFilmes.Api
COPY ./CopaMundoFilmes.Domain ./CopaMundoFilmes.Domain
WORKDIR /app/CopaMundoFilmes.Api
RUN dotnet restore
RUN dotnet publish -c Release -o /app/out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "CopaMundoFilmes.Api.dll"]